export const Add_SEARCH_MOVIE = "Add_SEARCH_MOVIE";
export const REMOVE_CLICK_MOVIE = "REMOVE_CLICK_MOVIE";
export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const REMOVE_MOVIE_FROM_STORAGE = "REMOVE_MOVIE_FROM_STORAGE";
export const FETCH_LIST_OF_MOVIES = "FETCH_LIST_OF_MOVIES";
// export const REMOVE_M